# Generated by Django 3.0.7 on 2020-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='images/')),
                ('article_topic', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
                ('article_demo_image', models.ImageField(upload_to='images/')),
                ('article_link', models.CharField(max_length=250)),
                ('art_cont_display', models.CharField(max_length=300)),
            ],
        ),
    ]
